services:
  - type: web
    name: autocorrect-tool
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    plan: free